"""Add is_helpful to APILog

Revision ID: 59b12ced73ca
Revises: 
Create Date: 2026-09-07 13:22:51.588521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b12ced73ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_logs', sa.Column('is_helpful', sa.Boolean(), nullable=True))
    op.alter_column('api_logs', 'prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_logs', 'response',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_logs', 'time_taken_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('api_logs', 'created_at')
    op.drop_column('api_logs', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_logs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_logs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('api_logs', 'time_taken_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('api_logs', 'response',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_logs', 'prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('api_logs', 'is_helpful')
    # ### end Alembic commands ###
